/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#004b1e',
        'primary-container': '#22c55e',
        'on-primary-fixed-variant': '#005321',
        'surface': '#faf8ff',
        'on-tertiary-container': '#860011',
        'tertiary-fixed': '#ffdad7',
        'on-secondary-fixed': '#341100',
        'on-primary': '#ffffff',
        'surface-bright': '#faf8ff',
        'on-primary-fixed': '#002109',
        'inverse-surface': '#283044',
        'on-tertiary-fixed-variant': '#930013',
        'inverse-primary': '#4ae176',
        'on-surface-variant': '#3d4a3d',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eef0ff',
        'on-error': '#ffffff',
        'surface-variant': '#dae2fd',
        'primary': '#006e2f',
        'surface-container-highest': '#dae2fd',
        'outline-variant': '#bccbb9',
        'primary-fixed': '#6bff8f',
        'on-secondary': '#ffffff',
        'surface-container': '#eaedff',
        'outline': '#6d7b6c',
        'on-background': '#131b2e',
        'surface-container-low': '#f2f3ff',
        'tertiary-container': '#ff8a83',
        'surface-container-lowest': '#ffffff',
        'secondary': '#9d4300',
        'on-tertiary-fixed': '#410004',
        'on-secondary-container': '#5c2400',
        'on-secondary-fixed-variant': '#783200',
        'surface-container-high': '#e2e7ff',
        'tertiary-fixed-dim': '#ffb3ad',
        'background': '#faf8ff',
        'on-surface': '#131b2e',
        'secondary-fixed-dim': '#ffb690',
        'error': '#ba1a1a',
        'tertiary': '#b91a24',
        'on-error-container': '#93000a',
        'surface-tint': '#006e2f',
        'primary-fixed-dim': '#4ae176',
        'surface-dim': '#d2d9f4',
        'secondary-fixed': '#ffdbca',
        'secondary-container': '#fd761a',
        'on-tertiary': '#ffffff',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'label-caps': ['Inter'],
        'headline-sm': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '25px', fontWeight: '600' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'body-lg': ['17px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['34px', { lineHeight: '41px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['15px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        'container-padding': '20px',
        'section-margin': '32px',
        'gutter': '16px',
        'unit': '4px',
        'card-gap': '12px',
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
